--PACKAGE
create or replace PACKAGE PKG_NBOARD

AS 
PROCEDURE PROC_NBOARD_VIEW ( O_CUR OUT SYS_REFCURSOR, IN_NB_NUM IN NUMBER);


END PKG_NBOARD;


--BODY
CREATE OR REPLACE
PACKAGE BODY PKG_NBOARD AS

  PROCEDURE PROC_NBOARD_VIEW ( 
O_CUR OUT SYS_REFCURSOR,
IN_NB_NUM IN NUMBER
) AS
  BEGIN
    UDPATE NOTICE_BOARD SET NB_CNT = NB_CNT + 1 
    WHERE NB_NUM = IN_NB_NUM;
    
    OPEN O_CUR FOR
    SELECT NB_TITLE, M.MEM_NICK, NB_CNT, NB_DATE, NB_CONT, NB_NUM
    FROM NOTICE_BOARD NB, MEMBER M
    WHERE NB.NB_NUM = IN_NB_NUM; 
 
 
  END PROC_NBOARD_VIEW;
